//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V3ToLogo.MODEL.DATABASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IVME_TRANSFER_BANKFICHE> IVME_TRANSFER_BANKFICHE { get; set; }
        public virtual DbSet<IVME_TRANSFER_BANKFICHE_ERR> IVME_TRANSFER_BANKFICHE_ERR { get; set; }
        public virtual DbSet<IVME_TRANSFER_CLFICHE> IVME_TRANSFER_CLFICHE { get; set; }
        public virtual DbSet<IVME_TRANSFER_CLFICHE_ERR> IVME_TRANSFER_CLFICHE_ERR { get; set; }
        public virtual DbSet<IVME_TRANSFER_CUSTOMER> IVME_TRANSFER_CUSTOMER { get; set; }
        public virtual DbSet<IVME_TRANSFER_CUSTOMER_ERR> IVME_TRANSFER_CUSTOMER_ERR { get; set; }
        public virtual DbSet<IVME_TRANSFER_INVOICE> IVME_TRANSFER_INVOICE { get; set; }
        public virtual DbSet<IVME_TRANSFER_INVOICE_ERR> IVME_TRANSFER_INVOICE_ERR { get; set; }
        public virtual DbSet<IVME_TRANSFER_PRODUCT> IVME_TRANSFER_PRODUCT { get; set; }
        public virtual DbSet<IVME_TRANSFER_PRODUCT_ERR> IVME_TRANSFER_PRODUCT_ERR { get; set; }
    
        public virtual ObjectResult<sp_IvmeCustomerList_Result> sp_IvmeCustomerList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_IvmeCustomerList_Result>("sp_IvmeCustomerList");
        }
    
        public virtual ObjectResult<sp_IvmeProductList_Result> sp_IvmeProductList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_IvmeProductList_Result>("sp_IvmeProductList");
        }
    
        public virtual ObjectResult<sp_CHF_KrediKarti_Result> sp_CHF_KrediKarti(string p_startdate, string p_enddate, string p_ficheNr)
        {
            var p_startdateParameter = p_startdate != null ?
                new ObjectParameter("p_startdate", p_startdate) :
                new ObjectParameter("p_startdate", typeof(string));
    
            var p_enddateParameter = p_enddate != null ?
                new ObjectParameter("p_enddate", p_enddate) :
                new ObjectParameter("p_enddate", typeof(string));
    
            var p_ficheNrParameter = p_ficheNr != null ?
                new ObjectParameter("p_ficheNr", p_ficheNr) :
                new ObjectParameter("p_ficheNr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CHF_KrediKarti_Result>("sp_CHF_KrediKarti", p_startdateParameter, p_enddateParameter, p_ficheNrParameter);
        }
    
        public virtual ObjectResult<sp_BankFicheList_Result> sp_BankFicheList(Nullable<int> ficheType, string p_startdate, string p_enddate, string p_ficheNr)
        {
            var ficheTypeParameter = ficheType.HasValue ?
                new ObjectParameter("ficheType", ficheType) :
                new ObjectParameter("ficheType", typeof(int));
    
            var p_startdateParameter = p_startdate != null ?
                new ObjectParameter("p_startdate", p_startdate) :
                new ObjectParameter("p_startdate", typeof(string));
    
            var p_enddateParameter = p_enddate != null ?
                new ObjectParameter("p_enddate", p_enddate) :
                new ObjectParameter("p_enddate", typeof(string));
    
            var p_ficheNrParameter = p_ficheNr != null ?
                new ObjectParameter("p_ficheNr", p_ficheNr) :
                new ObjectParameter("p_ficheNr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BankFicheList_Result>("sp_BankFicheList", ficheTypeParameter, p_startdateParameter, p_enddateParameter, p_ficheNrParameter);
        }
    
        public virtual ObjectResult<sp_IvmeInvoiceList_Result> sp_IvmeInvoiceList(string invoiceType, string p_startdate, string p_enddate, string p_invoiceNr)
        {
            var invoiceTypeParameter = invoiceType != null ?
                new ObjectParameter("invoiceType", invoiceType) :
                new ObjectParameter("invoiceType", typeof(string));
    
            var p_startdateParameter = p_startdate != null ?
                new ObjectParameter("p_startdate", p_startdate) :
                new ObjectParameter("p_startdate", typeof(string));
    
            var p_enddateParameter = p_enddate != null ?
                new ObjectParameter("p_enddate", p_enddate) :
                new ObjectParameter("p_enddate", typeof(string));
    
            var p_invoiceNrParameter = p_invoiceNr != null ?
                new ObjectParameter("p_invoiceNr", p_invoiceNr) :
                new ObjectParameter("p_invoiceNr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_IvmeInvoiceList_Result>("sp_IvmeInvoiceList", invoiceTypeParameter, p_startdateParameter, p_enddateParameter, p_invoiceNrParameter);
        }
    }
}
