//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V3ToLogo.MODEL.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVME_TRANSFER_CUSTOMER
    {
        public int ID { get; set; }
        public string CurrAccCode { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
    }
}
