//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToLogo.MODEL.LOGODB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVME_TRANSFER_PRODUCT
    {
        public int ID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
    }
}
