//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToLogo.MODEL.LOGODB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class LogoEntities : DbContext
    {
        public LogoEntities()
            : base("name=LogoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IVME_TRANSFER_CUSTOMER> IVME_TRANSFER_CUSTOMER { get; set; }
        public DbSet<IVME_TRANSFER_CUSTOMER_ERR> IVME_TRANSFER_CUSTOMER_ERR { get; set; }
        public DbSet<IVME_TRANSFER_INVOICE> IVME_TRANSFER_INVOICE { get; set; }
        public DbSet<IVME_TRANSFER_INVOICE_ERR> IVME_TRANSFER_INVOICE_ERR { get; set; }
        public DbSet<IVME_TRANSFER_PRODUCT> IVME_TRANSFER_PRODUCT { get; set; }
        public DbSet<IVME_TRANSFER_PRODUCT_ERR> IVME_TRANSFER_PRODUCT_ERR { get; set; }
    
        public virtual ObjectResult<sp_IvmeCustomerCommList_Result> sp_IvmeCustomerCommList(string cURRACCCODE)
        {
            var cURRACCCODEParameter = cURRACCCODE != null ?
                new ObjectParameter("CURRACCCODE", cURRACCCODE) :
                new ObjectParameter("CURRACCCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_IvmeCustomerCommList_Result>("sp_IvmeCustomerCommList", cURRACCCODEParameter);
        }
    
        public virtual ObjectResult<sp_IvmeCustomerList_Result> sp_IvmeCustomerList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_IvmeCustomerList_Result>("sp_IvmeCustomerList");
        }
    
        public virtual ObjectResult<sp_IvmeInvoiceList_Result> sp_IvmeInvoiceList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_IvmeInvoiceList_Result>("sp_IvmeInvoiceList");
        }
    
        public virtual ObjectResult<sp_IvmeProductList_Result> sp_IvmeProductList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_IvmeProductList_Result>("sp_IvmeProductList");
        }
    
        public virtual int sp_InvoiceTransferred(string invoiceNr, string invoiceType)
        {
            var invoiceNrParameter = invoiceNr != null ?
                new ObjectParameter("invoiceNr", invoiceNr) :
                new ObjectParameter("invoiceNr", typeof(string));
    
            var invoiceTypeParameter = invoiceType != null ?
                new ObjectParameter("invoiceType", invoiceType) :
                new ObjectParameter("invoiceType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InvoiceTransferred", invoiceNrParameter, invoiceTypeParameter);
        }
    }
}
